### Get categories
GET https://api.engagespot.co/v3/categories
X-Engagespot-Api-Key: 14b90lje36icbm6of8f64a
X-Engagespot-User-Id: hemanditwiz@gmail.com 

### Add Category

POST https://api.engagespot.co/v3/categories
X-Engagespot-Api-Key: 14b90lje36icbm6of8f64a
X-ENGAGESPOT-API-SECRET: 4s9omcnshtjkdt2mji1f9jbga44eh1589ccb8g75hejc8fia
X-Engagespot-User-Id: hemanditwiz@gmail.com 

{
    "name": "New Friend Requests"
}

### Send notification

POST https://api.engagespot.co/v3/notifications
Content-Type: application/json
X-Engagespot-Api-Key: 14b90lje36icbm6of8f64a
X-ENGAGESPOT-API-SECRET: 4s9omcnshtjkdt2mji1f9jbga44eh1589ccb8g75hejc8fia

{
  "notification": {
    "title": "yoasfdsdfsalooo",
    "createdAt":"2021-03"
  },
  "recipients": [
    "hemanditwiz@gmail.com"
  ],
  "data": {
      "type": "invoice",
      "url": "https://google.com"
    },
  "category": "hhhh"
}



### TypeSense

POST https://0mbtdiuf4sovc6g2p-1.a1.typesense.net/multi_search?x-typesense-api-key=VGITIeAMS8CjEXt2jNJ28SnimnFX5jxN
Content-Type: application/json
x-typesense-api-key: VGITIeAMS8CjEXt2jNJ28SnimnFX5jxN

{
    "searches": [
        {
            "collection": "engagespot_docs",
            "q": "eng",
            "query_by": "hierarchy.lvl0,hierarchy.lvl1,hierarchy.lvl2,hierarchy.lvl3,hierarchy.lvl4,hierarchy.lvl5,hierarchy.lvl6,content",
            "include_fields": "hierarchy.lvl0,hierarchy.lvl1,hierarchy.lvl2,hierarchy.lvl3,hierarchy.lvl4,hierarchy.lvl5,hierarchy.lvl6,content,anchor,url,type,id",
            "highlight_full_fields": "hierarchy.lvl0,hierarchy.lvl1,hierarchy.lvl2,hierarchy.lvl3,hierarchy.lvl4,hierarchy.lvl5,hierarchy.lvl6,content",
            "group_by": "url",
            "group_limit": 3,
            "filter_by": "language:=en && docusaurus_tag:=[default,docs-default-current]"
        }
    ]
}