export default {
  panel: {
    width: '30rem',
    height: '40rem',
    borderBottomLeftRadius: '11px',
    borderBottomRightRadius: '11px',
    borderTopLeftRadius: '11px',
    borderTopRightRadius: '11px',
    arrowSize: '10px',
    arrowInset: '-5px auto auto 0',
  },
  feed: {
    height: '30rem',
    placeholderTextSize: '1rem',
    placeholderMargin: '1rem 0 0 0',
    placeholderFontWeight: '300',
  },
  feedItem: {
    height: '30rem',
    padding: '0.5rem 0.7rem 0.5rem 0.7rem',
    placeholderTextSize: '1rem',
    notificationDotSize: '.5rem',
    imageSize: '4.5rem',
    imageRadius: '50%',
    hoverTransition: 'all 0.2s',
    textContentPadding: '0 .5rem 0 0',
    textContentMargin: '0 auto 0 1.2rem',
    headerFontWeight: '400',
    headerSize: '.9rem',
    headerPadding: '0 0 0.3rem 0',
    descriptionSize: '0.8rem',
    descriptionPadding: '0 0 0.3rem 0',
    dateSize: '.7rem',
    menuMargin: '0 1rem 0 0',
  },
  notificationButton: {
    iconSize: '1.5rem',
    outline: 'none',
    margin: '0',
    padding: '5px',
    borderWidth: '0',
    normalButtonRadius: '5px',
    floatingButtonRadius: '50%',
    transition: 'all .2s',
  },
  unreadBadgeCount: {
    background: 'red',
    borderRadius: '50%',
    fontSize: '.6rem',
    inset: '-4px -4px auto auto',
    size: '1rem',
  },
  dropdown: {
    iconWidth: '.5rem',
    iconHeight: '.6rem',
    margin: '0 .5rem 0 0',
    padding: '.5rem',
    borderWidth: '0',
    outline: 'none',
    transition: 'all 0.2s',
    menuBorderRadius: '2px',
    menuItemPadding: '0.5rem 0.7rem',
  },
  jumpToTop: {
    iconSize: '1rem',
    inset: '1.5rem 7rem auto auto',
    borderRadius: '50%',
    padding: '0.7rem',
    margin: '0',
    transition: 'all ease-in-out 0.5s',
  },
  header: {
    fontSize: '1rem',
    fontWeight: '400',
    height: '3rem',
    padding: '0.5rem 1rem',
    closeButtonOutline: 'none',
    closeButtonPadding: '5px',
    closeButtonFontSize: '1.6rem',
    closeButtonMargin: '0',
  },
  footer: {
    fontWeight: '400',
    height: '3rem',
    padding: '0.5rem 1rem',
    fontSize: '0.8rem',
    linkMargin: '0 0.5rem 0 auto',
    linkSize: '1.5rem',
    preferenceButtonMargin: '0 0 0 auto',
    preferenceButtonSize: '1.2rem',
    preferenceButtonPadding: '.2rem',
    preferenceButtonHoverTransition: 'all 0.2s',
    linkRadius: '3px',
  },
  preference: {
    height: '30rem',
    fontWeight: '400',
    padding: '1.2rem 2rem 1.2rem 2rem',
  },
  preferenceModal: {
    overlayOpacity: '.6',
    overlayMargin: '10% 0 0 0',
    height: '35%',
    backdropFilter: 'blur(1px)',
    borderRadius: '1.5rem 1.5rem 0 0',
    padding: '1.2rem 2rem 1.2rem 2rem',
    textAlign: 'center',
    headerMargin: '0 2rem',
    headerFontSize: '1rem',
    closeButtonSize: '.6rem',
    textPrimaryMargin: '0.5rem 2rem',
    textPrimaryFontSize: '.9rem',
    textSecondaryMargin: '1rem 0 0 0',
    textSecondaryFontSize: '.8rem',
    primaryButtonFontWeight: '600',
    primaryButtonPadding: '0.6rem 4.5rem',
    primaryButtonBorderRadius: '10px',
    primaryButtonMargin: '0.6rem 0 0.2rem 0',
    primaryButtonTransition: 'all 0.2s',
  },
};
