export default {
  colors: {
    brandingPrimary: 'rgb(0,191,166)',
    colorPrimary: '#282c34',
    colorSecondary: '#686868',
  },
  panel: {
    boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
    width: '30rem',
    height: '40rem',
    borderBottomLeftRadius: '5px',
    borderBottomRightRadius: '5px',
    borderTopLeftRadius: '5px',
    borderTopRightRadius: '5px',
    arrowSize: '10px',
    arrowInset: '-5px auto auto 0',
  },
  feed: {
    height: '30rem',
    background: 'white',
    placeholderTextSize: '1rem',
    placeholderTextColor: '#888888',
    placeholderMargin: '1rem 0 0 0',
    placeholderFontWeight: '300',
  },
  feedItem: {
    height: '30rem',
    padding: '0.5rem 0.7rem 0.5rem 0.7rem',
    border: '1px solid #edf4f2',
    background: 'white',
    placeholderTextSize: '1rem',
    notificationDot: 'green',
    notificationDotSize: '.5rem',
    imageSize: '4.5rem',
    imageRadius: '50%',
    hoverBackground: '#edf4f2',
    hoverTransition: 'all 0.2s',
    textContentPadding: '0 .5rem 0 0',
    textContentMargin: '0 auto 0 1.2rem',
    headerFontWeight: '400',
    headerSize: '1.0rem',
    headerPadding: '0 0 0.3rem 0',
    headerColor: '#282c34',
    descriptionSize: '0.9rem',
    descriptionColor: '#686868',
    descriptionPadding: '0 0 0.3rem 0',
    dateSize: '.7rem',
    dateColor: '#888888',
    menuMargin: '0 1rem 0 0',
    placeHolderBackground: 'rgb(230, 230, 230)',
    placeHolderGradient:
      'linear-gradient(to right, #eeeeee 10%, #dddddd 18%, #eeeeee 33%)',
  },
  notificationButton: {
    background: 'transparent',
    iconFill: '#ccc',
    iconSize: '1.5rem',
    outline: 'none',
    margin: '0',
    padding: '5px',
    borderWidth: '0',
    normalButtonRadius: '5px',
    floatingButtonRadius: '50%',
    floatingButtonShadow:
      '0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23)',
  },
  unreadBadgeCount: {
    background: 'red',
    borderRadius: '50%',
    color: 'white',
    fontSize: '.6rem',
    inset: '-4px -4px auto auto',
    size: '1rem',
  },
  dropdown: {
    iconFill: '#888888',
    iconWidth: '.5rem',
    iconHeight: '.6rem',
    margin: '0 .5rem 0 0',
    padding: '.5rem',

    borderWidth: '0',
    outline: 'none',
    background: 'transparent',
    transition: 'all 0.2s',
    hoverBackground: 'rgb(230, 230, 230)',
    menuBackground: 'white',
    menuShadow: '0 0 8px 0 rgba(0, 0, 0, 0.14)',
    menuItemTextColor: '#282c34',
    menuBorderRadius: '2px',
    menuItemHoverBackground: '#edf4f2',
    menuItemPadding: '0.5rem 0.7rem',
  },
  jumpToTop: {
    background: 'white',
    iconFill: '#888888',
    iconSize: '1rem',
    inset: '1.5rem 7rem auto auto',
    shadow: '0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23)',
    borderRadius: '50%',
    padding: '0.7rem',
    margin: '0',
    transition: 'all ease-in-out 0.5s',
  },
  header: {
    fontColor: 'white',
    fontSize: '1.2rem',
    fontWeight: '400',
    height: '2.5rem',
    padding: '0.5rem 1rem',
    closeButtonOutline: 'none',
    closeButtonPadding: '5px',
    closeButtonFontSize: '2rem',
    closeButtonMargin: '0',
    closeButtonBackground: 'transparent',
  },
  footer: {
    background: 'white',
    fontColor: '#888888',
    fontWeight: '400',
    height: '2.5rem',
    padding: '0.5rem 1rem',
    border: '1px solid rgb(230, 230, 230)',
    fontSize: '0.9rem',
    linkMargin: '0 0.5rem 0 0',
    linkSize: '1.5rem',
    linkRadius: '3px',
  },
};
