name: tests
on: [pull_request, push]
jobs:
  test:
    name: 'Test (node ${{ matrix.node }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
          pnpm install
          pnpm test:ci
